spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/mealplandb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}spring.datasource.username=${SPRING_DATASOURCE_USERNAME: root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD: rootpassword}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring. ipa. database-platform=org.hibernate.dialect.MySOLDialect