spring.application.name=mealplan-service

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.sql.init.mode=always
# If COURSE_SERVICE URL exists, use it. Otherwise use http://localhost: 8081
# COURSE_SERVICE_URL will be set by Docker when running the container
nutritionservice.service.url=${NUTRITIONSERVICE_SERVICE_URL:http://localhost:8081}